name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    permissions: write-all
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: Mods/
          dest: modpack.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Stardew Modpack"
          files: |
            *.zip
            *.ps1
